title: JUSSAA
description: The Junior & Senior School Alumni Association

url: "https://jussaa.org"
baseurl: ""

markdown: kramdown

collections:
  news:
    output: true
    permalink: /news/:name/
  events:
    output: true
    permalink: /events/:name/

exclude:
  - .devcontainer
  - vendor
  - scripts
  - README.md
  - MAINTAINING.md
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
