title: JUSSAA
description: The Junior & Senior School Alumni Association

url: "https://jussaa.org"
baseurl: ""

markdown: kramdown

exclude:
  - .devcontainer
  - scripts
  - README.md
  - MAINTAINING.md
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
