title: JUSSAA
description: The Junior & Senior School Alumni Association

url: "https://jussaa.org"
production_url: "https://jussaa.org"
baseurl: ""
future: true

markdown: kramdown

collections:
  news:
    output: true
    permalink: /news/:name/
  events:
    output: true
    permalink: /events/:name/

exclude:
  - .devcontainer
  - node_modules
  - package.json
  - package-lock.json
  - playwright.config.ts
  - tests
  - test-results
  - playwright-report
  - vendor
  - scripts
  - README.md
  - MAINTAINING.md
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
